### ISSUE TITLE
[Feature request]: Using mongodump instead of mongoexport

### ISSUE THREAD

**Issue by www-chique** [euberdeveloper/mongoback#15]
Hey! I love this package. It helped me a lot. Thanks for all the hard and talented work you've put into it.

I was wondering if there's a way to use ``mongodump` instead of `mongoexport`?
While working on the PR: #14 , I found out that it would be relatively easy to implement, if there's an option to specify `method`, either "mongoexport (default)" or "mongodump" into the configuration, and it will just run the final execution accordingly.

Reason: Apparently [mongodump generates smaller, faster and efficient backup](https://stackoverflow.com/a/63720871/1914985) at times. 

For example, in the following line, the "mongoexport" can be swapped with "mongodump", according to a configuration.
I tried to implement this in a PR myself, and made okay progress, until I stumbled upon the `checkMongoexportInstalled` function, which is too tightly bound to the "mongoexport", and is used inside tests and many other places.
So instead of breaking things, I thought I'll just make you a request, as you have a lot better knowledge regarding this matter.

https://github.com/euberdeveloper/mongoback/blob/10ed110bfa7ffb5b93a2770cbb96f395402415d8/source/utils/exportCollections/getCommand.ts#L146

This could be something like
```
const method = parseGenericString(options, 'method'); // mongoexport | mongodump
let command = `${method}${uri}${host}${port}${username}${password}${db}${collection}${ssl}${sslCAFile}${sslPEMKeyFile}${sslPEMKeyPassword}${sslCRLFile}${sslAllowInvalidCertificates}${sslAllowInvalidHostnames}${sslFIPSMode}${authenticationMechanism}${gssapiServiceName}${gssapiHostName}${authenticationDatabase}${readPreference}${verbose}${quiet}${ipv6}${fields}${fieldFile}${query}${type}${jsonFormat}${jsonArray}${pretty}${noHeaderLine}${slaveOk}${dbpath}${directoryperdb}${forceTableScan}${skip}${limit}${sort}${out}`;
    return command;
```

**Comment by euberdeveloper** [comment]
I think you are right, I planned to do it some time ago, but I did not find the time to do it. The name "mongoback" was thought for every type of backup indeed

Actually also a frontend in Vuejs that uses mongoback under the hood was planned

If I'll find the time I will do both, but of course any contribution is well accepted

**Comment by euberdeveloper** [comment]
For the usage as a module I could add "mongoDump" function, while for the CLI adding a subcommand with yargs

**Comment by www-chique** [comment]
> I think you are right, I planned to do it some time ago, but I did not find the time to do it. The name "mongoback" was thought for every type of backup indeed
> 
> Actually also a frontend in Vuejs that uses mongoback under the hood was planned
> 
> If I'll find the time I will do both, but of course any contribution is well accepted

I tried something at #17 . Let me know what you think. Please feel free to modify and do your own thing. I hope I helped a little bit somewhere.

**Comment by www-chique** [comment]
I'll close this one for now, as the feature is already merged.

Until someone needs to use the options which doesn't exist in the list of common functions between mongodump and mongoexport, we can keep using the existing system where you can set "mongodump" by passing a `method: mongodump` in the config.

**Comment by euberdeveloper** [comment]
Ok, I think that in one or two weeks I will be able to extend it to a full support for mongoDump
